---

dependency:
  name: galaxy
  options:
    role-file: molecule/resources/requirements.yml
driver:
  name: docker
lint:
  name: yamllint
  options:
    config-file: molecule/resources/yaml-lint.yml
platforms:
  - name: instance-1
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos7}-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-"sleep infinity"}
    pre_build_image: true
    groups:
      - common
      - download
      - remove
provisioner:
  name: ansible
  config_options:
    defaults:
      retry_files_enabled: false
      host_key_checking: false
  inventory:
    group_vars:
      common:
        f5app_services_package_server: ${F5_DEVICE_HOST:-localhost}
        f5app_services_package_server_port: ${F5_DEVICE_PORT:-443}
        f5app_services_package_user: ${F5_DEVICE_USER:-admin}
        f5app_services_package_password: ${F5_DEVICE_PASSWORD:-localhost}
        f5app_services_package_validate_certs: ${F5_VALIDATE_CERT:-false}
        f5app_services_package_transport: ${F5_DEVICE_TRANSPORT:-rest}
      download:
        f5app_services_package_state: present
      remove:
        f5app_services_package_state: absent
  env:
    ANSIBLE_ROLES_PATH: ../../../
  lint:
    name: ansible-lint
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-playbook.yml}
scenario:
  name: download-install-remove
verifier:
  name: testinfra
  lint:
    name: flake8
