---

- name: Download and install-remove RPM packages
  hosts: all
  roles:
    - role: f5devcentral.f5app_services_package

- name: Download and Install RPMs
  hosts: download
  any_errors_fatal: true

  tasks:
    - name: Download and Install AS3 RPM no sha check
      include_role:
        name: f5devcentral.f5app_services_package
      vars:
        f5app_services_package_url: "https://github.com/F5Networks/f5-appsvcs-extension/raw/master/dist/latest/f5-appsvcs-3.9.0-3.noarch.rpm"
        f5app_services_package_path: "/tmp/f5-appsvcs-3.9.0-3.noarch.rpm"

    - name: Download and Install DO RPM sha check - url
      include_role:
        name: f5devcentral.f5app_services_package
      vars:
        f5app_services_package_url: "https://github.com/F5Networks/f5-declarative-onboarding/raw/master/dist/f5-declarative-onboarding-1.3.0-4.noarch.rpm"
        f5app_services_package_checksum_url: "https://github.com/F5Networks/f5-declarative-onboarding/raw/master/dist/f5-declarative-onboarding-1.3.0-4.noarch.rpm.sha256"
        f5app_services_package_path: "/tmp/f5-declarative-onboarding-1.3.0-4.noarch.rpm"

    - name: Download and Install TS RPM sha check - no_url
      include_role:
        name: f5devcentral.f5app_services_package
      vars:
        f5app_services_package_url: "https://github.com/F5Networks/f5-telemetry-streaming/raw/master/dist/f5-telemetry-1.1.0-1.noarch.rpm"
        f5app_services_package_path: "/tmp/f5-telemetry-1.1.0-1.noarch.rpm"
        f5app_services_package_checksum: "7fdad5ff409ca7068f75a19c38d1b06d3f4facb86afce15976af63b963c03e29"

- name: Remove RPMs
  hosts: remove
  any_errors_fatal: true

  tasks:
    - name: Remove AS3 RPM
      include_role:
        name: f5devcentral.f5app_services_package
      vars:
        f5app_services_package_path: "/tmp/f5-appsvcs-3.9.0-3.noarch.rpm"

    - name: Remove DO RPM
      include_role:
        name: f5devcentral.f5app_services_package
      vars:
        f5app_services_package_path: "/tmp/f5-declarative-onboarding-1.3.0-4.noarch.rpm"

    - name: Remove TS RPM
      include_role:
        name: f5devcentral.f5app_services_package
      vars:
        f5app_services_package_path: "/tmp/f5-telemetry-1.1.0-1.noarch.rpm"
