---

- name: Install and Remove RPM packages
  hosts: all
  roles:
    - role: f5devcentral.f5app_services_package

- name: Install RPMs
  hosts: install
  any_errors_fatal: true

  tasks:
    - name: Install AS3 RPM
      include_role:
        name: f5devcentral.f5app_services_package
      vars:
        f5app_services_package_path: "/tmp/f5-appsvcs-3.9.0-3.noarch.rpm"

    - name: Install DO RPM
      include_role:
        name: f5devcentral.f5app_services_package
      vars:
        f5app_services_package_path: "/tmp/f5-declarative-onboarding-1.3.0-4.noarch.rpm"

    - name: Install TS RPM
      include_role:
        name: f5devcentral.f5app_services_package
      vars:
        f5app_services_package_path: "/tmp/f5-telemetry-1.1.0-1.noarch.rpm"


- name: Remove RPMs
  hosts: remove
  any_errors_fatal: true

  tasks:
    - name: Remove AS3 RPM
      include_role:
        name: f5devcentral.f5app_services_package
      vars:
        f5app_services_package_path: "/tmp/f5-appsvcs-3.9.0-3.noarch.rpm"

    - name: Remove DO RPM
      include_role:
        name: f5devcentral.f5app_services_package
      vars:
        f5app_services_package_path: "/tmp/f5-declarative-onboarding-1.3.0-4.noarch.rpm"

    - name: Remove TS RPM
      include_role:
        name: f5devcentral.f5app_services_package
      vars:
        f5app_services_package_path: "/tmp/f5-telemetry-1.1.0-1.noarch.rpm"
